In [2]:
import pandas as pd
import numpy as np

In [3]:
ages = pd.Series([22, 35, 58, 45, 18, 27, 33, 41])

ages

0    22
1    35
2    58
3    45
4    18
5    27
6    33
7    41
dtype: int64

In [5]:
marks = pd.Series([85, 92, 78, 90, 88, 95, 80, 87], index=['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah'])

marks

Alice      85
Bob        92
Charlie    78
David      90
Eva        88
Frank      95
Grace      80
Hannah     87
dtype: int64

In [6]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
}

df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [9]:
print("df.head(3)", df.head(3))  # Display the first few rows of the DataFrame
print("df.describe()", df.describe())  # Get summary statistics of the DataFrame
print("df.info()", df.info())  # Get information about the DataFrame, including data types and non-null counts
print("df.shape", df.shape)  # Get the shape of the DataFrame (rows, columns)
print("df.columns", df.columns)  # Get the column names of the DataFrame
print("df['Name']", df['Name'])  # Access a specific column by name
print("df.index", df.index)  # Get the index of the DataFrame
print("df.dtypes", df.dtypes)  # Get the data types of each column in the DataFrame

df.head(3)       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
df.describe()              Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes
df.info() None
df.shape (5, 3)
df.columns Index(['Name', 'Age', 'City'], dtype='object')
df['Name'] 0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object
df.index RangeIndex(start=0, stop=5, step=1)
df.dtypes Name    object
Age      int64
City    object
dtype: object

In [10]:
df = pd.read_csv('../titanic.csv')

df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [11]:
df['Name']

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [12]:
df.loc[0]  # Access the first row of the DataFrame using .loc

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

In [13]:
df.loc[0, 'Name']

'Mr. Owen Harris Braund'

In [14]:
df.loc[0:1, ['Name', 'Age']]  # Access specific rows and columns using .loc

                                                Name   Age
0                             Mr. Owen Harris Braund  22.0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0

In [15]:
df.iloc[0]

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

In [22]:
df.rename(columns={"Name": "Full Name"}, inplace=True)

df

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
Name,,,,,,,,,
Mr. Owen Harris Braund,0,0,0,3,male,22.0,1,0,7.2500
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833
Miss. Laina Heikkinen,2,2,1,3,female,26.0,0,0,7.9250
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...,...
Rev. Juozas Montvila,882,882,0,2,male,27.0,0,0,13.0000
Miss. Margaret Edith Graham,883,883,1,1,female,19.0,0,0,30.0000
Miss. Catherine Helen Johnston,884,884,0,3,female,7.0,1,2,23.4500
Mr. Karl Howell Behr,885,885,1,1,male,26.0,0,0,30.0000
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500

In [23]:
df["Bonus"] = 5000
df

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Bonus
Name,,,,,,,,,,
Mr. Owen Harris Braund,0,0,0,3,male,22.0,1,0,7.2500,5000
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833,5000
Miss. Laina Heikkinen,2,2,1,3,female,26.0,0,0,7.9250,5000
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000,5000
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500,5000
...,...,...,...,...,...,...,...,...,...,...
Rev. Juozas Montvila,882,882,0,2,male,27.0,0,0,13.0000,5000
Miss. Margaret Edith Graham,883,883,1,1,female,19.0,0,0,30.0000,5000
Miss. Catherine Helen Johnston,884,884,0,3,female,7.0,1,2,23.4500,5000
Mr. Karl Howell Behr,885,885,1,1,male,26.0,0,0,30.0000,5000
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500,5000

In [24]:
df['Class'] = df['Pclass'].map({1: 'First', 2: 'Second', 3: 'Third'})
df

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Bonus,Class
Name,,,,,,,,,,,
Mr. Owen Harris Braund,0,0,0,3,male,22.0,1,0,7.2500,5000,Third
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833,5000,First
Miss. Laina Heikkinen,2,2,1,3,female,26.0,0,0,7.9250,5000,Third
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000,5000,First
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500,5000,Third
...,...,...,...,...,...,...,...,...,...,...,...
Rev. Juozas Montvila,882,882,0,2,male,27.0,0,0,13.0000,5000,Second
Miss. Margaret Edith Graham,883,883,1,1,female,19.0,0,0,30.0000,5000,First
Miss. Catherine Helen Johnston,884,884,0,3,female,7.0,1,2,23.4500,5000,Third
Mr. Karl Howell Behr,885,885,1,1,male,26.0,0,0,30.0000,5000,First
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500,5000,Third

In [25]:
df["Survived Status"] = df["Survived"].map({0: 'Did not survive', 1: 'Survived'})
df

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Bonus,Class,Survived Status
Name,,,,,,,,,,,,
Mr. Owen Harris Braund,0,0,0,3,male,22.0,1,0,7.2500,5000,Third,Did not survive
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833,5000,First,Survived
Miss. Laina Heikkinen,2,2,1,3,female,26.0,0,0,7.9250,5000,Third,Survived
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000,5000,First,Survived
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500,5000,Third,Did not survive
...,...,...,...,...,...,...,...,...,...,...,...,...
Rev. Juozas Montvila,882,882,0,2,male,27.0,0,0,13.0000,5000,Second,Did not survive
Miss. Margaret Edith Graham,883,883,1,1,female,19.0,0,0,30.0000,5000,First,Survived
Miss. Catherine Helen Johnston,884,884,0,3,female,7.0,1,2,23.4500,5000,Third,Did not survive
Mr. Karl Howell Behr,885,885,1,1,male,26.0,0,0,30.0000,5000,First,Survived
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500,5000,Third,Did not survive

In [27]:
df["Status"] = df["Age"].apply(lambda x: 'Adult' if x >= 18 else 'Minor')
df

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Bonus,Class,Survived Status,Status
Name,,,,,,,,,,,,,
Mr. Owen Harris Braund,0,0,0,3,male,22.0,1,0,7.2500,5000,Third,Did not survive,Adult
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833,5000,First,Survived,Adult
Miss. Laina Heikkinen,2,2,1,3,female,26.0,0,0,7.9250,5000,Third,Survived,Adult
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000,5000,First,Survived,Adult
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500,5000,Third,Did not survive,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Rev. Juozas Montvila,882,882,0,2,male,27.0,0,0,13.0000,5000,Second,Did not survive,Adult
Miss. Margaret Edith Graham,883,883,1,1,female,19.0,0,0,30.0000,5000,First,Survived,Adult
Miss. Catherine Helen Johnston,884,884,0,3,female,7.0,1,2,23.4500,5000,Third,Did not survive,Minor
Mr. Karl Howell Behr,885,885,1,1,male,26.0,0,0,30.0000,5000,First,Survived,Adult
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500,5000,Third,Did not survive,Adult

In [28]:
df[df['Age'] > 30]

,level_0,index,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Bonus,Class,Survived Status,Status
Name,,,,,,,,,,,,,
Mrs. John Bradley (Florence Briggs Thayer) Cumings,1,1,1,1,female,38.0,1,0,71.2833,5000,First,Survived,Adult
Mrs. Jacques Heath (Lily May Peel) Futrelle,3,3,1,1,female,35.0,1,0,53.1000,5000,First,Survived,Adult
Mr. William Henry Allen,4,4,0,3,male,35.0,0,0,8.0500,5000,Third,Did not survive,Adult
Mr. Timothy J McCarthy,6,6,0,1,male,54.0,0,0,51.8625,5000,First,Did not survive,Adult
Miss. Elizabeth Bonnell,11,11,1,1,female,58.0,0,0,26.5500,5000,First,Survived,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mr. Victor Vander Cruyssen,869,869,0,3,male,47.0,0,0,9.0000,5000,Third,Did not survive,Adult
Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,875,875,1,1,female,56.0,0,1,83.1583,5000,First,Survived,Adult
Mr. Johann Markun,877,877,0,3,male,33.0,0,0,7.8958,5000,Third,Did not survive,Adult
Mrs. William (Margaret Norton) Rice,881,881,0,3,female,39.0,0,5,29.1250,5000,Third,Did not survive,Adult
Mr. Patrick Dooley,886,886,0,3,male,32.0,0,0,7.7500,5000,Third,Did not survive,Adult

In [30]:
df.duplicated().sum()

np.int64(0)