Problem 1: DataFrame create করো

In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Heidi"],
    "Age": [25, 30, 35, 40, 45, 50, 55, 60],
    "Email": ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com", "eve@example.com", "frank@example.com", "grace@example.com", "heidi@example.com"]
}

df = pd.DataFrame(data)
df

      Name  Age                Email
0    Alice   25    alice@example.com
1      Bob   30      bob@example.com
2  Charlie   35  charlie@example.com
3    David   40    david@example.com
4      Eve   45      eve@example.com
5    Frank   50    frank@example.com
6    Grace   55    grace@example.com
7    Heidi   60    heidi@example.com

Problem 2: শুধু Name column print করো

In [3]:
print(df["Name"])  # Display the DataFrame

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7      Heidi
Name: Name, dtype: object

In [5]:
df.loc[:, ["Name"]]

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve
5    Frank
6    Grace
7    Heidi

Problem 3: Age 25 এর বেশি যাদের, তাদের বের করো

In [6]:
df[df["Age"] > 25]

      Name  Age                Email
1      Bob   30      bob@example.com
2  Charlie   35  charlie@example.com
3    David   40    david@example.com
4      Eve   45      eve@example.com
5    Frank   50    frank@example.com
6    Grace   55    grace@example.com
7    Heidi   60    heidi@example.com

Problem 4: New column add করো

In [7]:
df["Country"] = "Bangladesh"  # Add a new column "Country" with a default value
df

      Name  Age                Email     Country
0    Alice   25    alice@example.com  Bangladesh
1      Bob   30      bob@example.com  Bangladesh
2  Charlie   35  charlie@example.com  Bangladesh
3    David   40    david@example.com  Bangladesh
4      Eve   45      eve@example.com  Bangladesh
5    Frank   50    frank@example.com  Bangladesh
6    Grace   55    grace@example.com  Bangladesh
7    Heidi   60    heidi@example.com  Bangladesh

Problem 5: Age descending order এ sort করো

In [8]:
df_sorted = df.sort_values(by="Age", ascending=False)  # Sort the DataFrame by "Age" in descending order
df_sorted

      Name  Age                Email     Country
7    Heidi   60    heidi@example.com  Bangladesh
6    Grace   55    grace@example.com  Bangladesh
5    Frank   50    frank@example.com  Bangladesh
4      Eve   45      eve@example.com  Bangladesh
3    David   40    david@example.com  Bangladesh
2  Charlie   35  charlie@example.com  Bangladesh
1      Bob   30      bob@example.com  Bangladesh
0    Alice   25    alice@example.com  Bangladesh

Problem 6: Missing value fill করো

In [14]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, None, 30]
}

df = pd.DataFrame(data)
df
df.isnull().sum()  # Count the number of missing values in each column

df[df["Age"].isnull()]  # Display rows where "Age" is missing

df["Age"].fillna(df["Age"].mean(), inplace=True)  # Fill missing values in "Age" with the mean of the column
df

/var/folders/lw/z8wm5rq94_93m066pccb71jm0000gn/T/ipykernel_95218/1383644475.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)  # Fill missing values in "Age" with the mean of the column

  Name   Age
0    A  20.0
1    B  25.0
2    C  30.0

Problem 7: Duplicate remove করো

In [15]:
data = {
    "Name": ["A", "B", "A"],
    "Age": [20, 25, 20]
}

df = pd.DataFrame(data)
df.drop_duplicates(inplace=True)

df

  Name  Age
0    A   20
1    B   25

Problem 8: Group by করে average salary বের করো

In [16]:
data = {
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 60000, 45000]
}

df = pd.DataFrame(data)

result = df.groupby("Department")["Salary"].mean()
print(result)

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

Problem 9: City অনুযায়ী count বের করো

In [17]:
data = {
    "City": ["Dhaka", "Sylhet", "Dhaka", "Khulna", "Dhaka"]
}

df = pd.DataFrame(data)
result = df["City"].value_counts()
print(result)

City
Dhaka     3
Sylhet    1
Khulna    1
Name: count, dtype: int64

Problem 10: apply দিয়ে salary category বানাও

In [18]:
data = {
    "Name": ["A", "B", "C"],
    "Salary": [30000, 60000, 90000]
}

df = pd.DataFrame(data)

def category(salary):
    if salary >= 80000:
        return "High"
    elif salary >= 50000:
        return "Medium"
    else:
        return "Low"

df["Category"] = df["Salary"].apply(category)

print(df)

  Name  Salary Category
0    A   30000      Low
1    B   60000   Medium
2    C   90000     High