In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./../pandas_A_to_Z_practice_dataset.csv')

df

,Employee_ID,Full_Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Phone,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,1736687537,NaN,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,1620576383,NaN,144714,3.2,23,9,No,Software,Cash,2025-04-11
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,1472043515,NaN,99471,3.2,35,3,No,Software,Card,2024-03-06
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,1888461803,NaN,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,1882070937,NaN,196838,3.2,21,1,No,Training,Card,2026-07-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,1312941099,EMP-0003,615104,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,1499326148,EMP-0003,396764,3.3,18,2,No,Software,Mobile Banking,2024-03-07
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,1537415205,EMP-0006,62570,3.2,8,10,No,Training,Bank Transfer,2024-05-28
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,1464549859,EMP-0008,145536,4.4,30,10,No,Training,Cash,2024-07-09
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,1677839607,EMP-0008,63105,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18

In [8]:
df.shape
df.shape[1]

31

In [11]:
# rows and column accessing

df.head(5)

,Employee_ID,Full_Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Phone,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,1736687537,NaN,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,1620576383,NaN,144714,3.2,23,9,No,Software,Cash,2025-04-11
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,1472043515,NaN,99471,3.2,35,3,No,Software,Card,2024-03-06
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,1888461803,NaN,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,1882070937,NaN,196838,3.2,21,1,No,Training,Card,2026-07-18

In [13]:
df.tail(5)

,Employee_ID,Full_Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Phone,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,1312941099,EMP-0003,615104,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,1499326148,EMP-0003,396764,3.3,18,2,No,Software,Mobile Banking,2024-03-07
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,1537415205,EMP-0006,62570,3.2,8,10,No,Training,Bank Transfer,2024-05-28
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,1464549859,EMP-0008,145536,4.4,30,10,No,Training,Cash,2024-07-09
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,1677839607,EMP-0008,63105,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18

In [14]:
df.loc[0]  # Access the first row of the DataFrame using .loc

Employee_ID                              EMP-0001
Full_Name                             Sakib Akter
Gender                                       Male
Age                                          28.0
Department                                  Sales
Job_Title                         Sales Executive
City                                   Chittagong
Region                                 South-East
Country                                Bangladesh
Join_Date                              2024-08-03
Last_Promotion_Date                           NaN
Salary_BDT                               113000.0
Bonus_Percent                                0.03
Performance_Score                             3.8
Experience_Years                                1
Training_Hours                                  3
Projects_Completed                              2
Remote_Work                                   Yes
Employment_Status                          Active
Education_Level                               HSC
Email                    sakib.akter1@example.com
Phone                                  1736687537
Manager_ID                                    NaN
Sales_BDT                                  750800
Customer_Rating                               4.1
Overtime_Hours                                 34
Sick_Days                                       6
Has_Missing_Documents                          No
Product_Category                         Training
Payment_Method                      Bank Transfer
Order_Date                             2024-01-14
Name: 0, dtype: object

In [15]:
df.loc[0:5]  # Access the first five rows of the DataFrame using .loc

,Employee_ID,Full_Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Phone,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,1736687537,NaN,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,1620576383,NaN,144714,3.2,23,9,No,Software,Cash,2025-04-11
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,1472043515,NaN,99471,3.2,35,3,No,Software,Card,2024-03-06
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,1888461803,NaN,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,1882070937,NaN,196838,3.2,21,1,No,Training,Card,2026-07-18
5,EMP-0006,Tanjila Khan,Female,37.0,HR,HR Manager,Rajshahi,North-West,Bangladesh,2024-03-02,...,1612614124,NaN,29325,4.8,19,3,Yes,Hardware,Cash,2024-06-24

In [17]:
df.loc[0, "Full_Name"]

'Sakib Akter'

In [19]:
df.loc[0:1, ['Full_Name', 'Age']]  # Access specific rows and columns using .loc

          Full_Name   Age
0       Sakib Akter  28.0
1  Farhan Chowdhury  29.0

In [20]:
df.iloc[0]

Employee_ID                              EMP-0001
Full_Name                             Sakib Akter
Gender                                       Male
Age                                          28.0
Department                                  Sales
Job_Title                         Sales Executive
City                                   Chittagong
Region                                 South-East
Country                                Bangladesh
Join_Date                              2024-08-03
Last_Promotion_Date                           NaN
Salary_BDT                               113000.0
Bonus_Percent                                0.03
Performance_Score                             3.8
Experience_Years                                1
Training_Hours                                  3
Projects_Completed                              2
Remote_Work                                   Yes
Employment_Status                          Active
Education_Level                               HSC
Email                    sakib.akter1@example.com
Phone                                  1736687537
Manager_ID                                    NaN
Sales_BDT                                  750800
Customer_Rating                               4.1
Overtime_Hours                                 34
Sick_Days                                       6
Has_Missing_Documents                          No
Product_Category                         Training
Payment_Method                      Bank Transfer
Order_Date                             2024-01-14
Name: 0, dtype: object

In [21]:
df.iloc[0, 0]

'EMP-0001'

In [22]:
df.iloc[0:2, 0:2]  # Access specific rows and columns using .iloc

  Employee_ID         Full_Name
0    EMP-0001       Sakib Akter
1    EMP-0002  Farhan Chowdhury

In [23]:
df.rename(columns={"Full_Name": "Name"}, inplace=True)

df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Phone,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,1736687537,NaN,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,1620576383,NaN,144714,3.2,23,9,No,Software,Cash,2025-04-11
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,1472043515,NaN,99471,3.2,35,3,No,Software,Card,2024-03-06
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,1888461803,NaN,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,1882070937,NaN,196838,3.2,21,1,No,Training,Card,2026-07-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,1312941099,EMP-0003,615104,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,1499326148,EMP-0003,396764,3.3,18,2,No,Software,Mobile Banking,2024-03-07
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,1537415205,EMP-0006,62570,3.2,8,10,No,Training,Bank Transfer,2024-05-28
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,1464549859,EMP-0008,145536,4.4,30,10,No,Training,Cash,2024-07-09
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,1677839607,EMP-0008,63105,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18

In [27]:
df["Bonus"] = df["Sales_BDT"] * 0.07  # Create a new column 'Bonus' based on the 'Sales_BDT' column
df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Manager_ID,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,NaN,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14,52556.00
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,NaN,144714,3.2,23,9,No,Software,Cash,2025-04-11,10129.98
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,NaN,99471,3.2,35,3,No,Software,Card,2024-03-06,6962.97
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,NaN,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05,31447.15
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,NaN,196838,3.2,21,1,No,Training,Card,2026-07-18,13778.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,EMP-0003,615104,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,EMP-0003,396764,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,EMP-0006,62570,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,EMP-0008,145536,4.4,30,10,No,Training,Cash,2024-07-09,10187.52
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,EMP-0008,63105,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18,4417.35

In [28]:
df["Total_Salary"] = df["Salary_BDT"] + df["Bonus"]  # Create a new column 'Total_Salary' based on the 'Salary_BDT' and 'Bonus' columns
df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Sales_BDT,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,750800,4.1,34,6,No,Training,Bank Transfer,2024-01-14,52556.00,165556.00
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,144714,3.2,23,9,No,Software,Cash,2025-04-11,10129.98,98129.98
2,EMP-0003,Imran Rahman,Female,24.0,Data,ML Intern,Comilla,East,Bangladesh,2024-02-17,...,99471,3.2,35,3,No,Software,Card,2024-03-06,6962.97,59962.97
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,449245,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05,31447.15,136947.15
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,196838,3.2,21,1,No,Training,Card,2026-07-18,13778.66,101778.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,615104,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28,146057.28
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,396764,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,62570,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,145536,4.4,30,10,No,Training,Cash,2024-07-09,10187.52,90687.52
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,63105,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18,4417.35,57417.35

In [31]:
df["Status"] = df["Age"].apply(lambda x: "Adult" if x > 18 else "Minor")  # Create a new column 'Status' based on the 'Age' column
df.sample(5)  # Display a random sample of 5 rows from the DataFrame

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
10,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90,Adult
122,EMP-0123,Hasan Islam,Female,28.0,Sales,Account Manager,Dhaka,Central,Bangladesh,2025-07-27,...,3.9,12,12,No,Support Plan,Bank Transfer,2024-12-25,41665.75,159665.75,Adult
64,EMP-0065,Rafi Islam,Female,28.0,Operations,Supply Chain Officer,Rangpur,North,Bangladesh,2023-05-13,...,4.1,15,1,Yes,Hardware,Mobile Banking,2026-07-18,5768.98,128768.98,Adult
43,EMP-0044,Sadia Hossain,Female,39.0,Sales,Sales Executive,Khulna,South-West,Bangladesh,2023-07-30,...,4.7,8,0,No,Hardware,Bank Transfer,2024-02-02,48521.83,111521.83,Adult
16,EMP-0017,Sadia Begum,Male,42.0,HR,HR Manager,Rajshahi,North-West,Bangladesh,2022-09-09,...,3.9,0,4,No,Hardware,Mobile Banking,2025-10-21,7451.50,140451.50,Adult

In [32]:
df.sort_values(by="Total_Salary", ascending=False)  # Sort the DataFrame by the 'Total_Salary' column in descending order

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
38,EMP-0039,Mehjabin Khan,Female,NaN,Support,Customer Success Executive,Rajshahi,North-West,Bangladesh,2024-03-02,...,3.2,18,0,No,Consulting,Cash,2024-04-10,42191.31,180191.31,Minor
52,EMP-0053,Hasan Rahman,Female,29.0,Finance,Sales Executive,Sylhet,North-East,Bangladesh,2025-07-11,...,3.3,28,1,No,Training,Bank Transfer,2025-07-16,46037.95,176537.95,Adult
110,EMP-0111,Arif Ahmed,Female,28.0,Marketing,Brand Executive,Chittagong,South-East,Bangladesh,2019-10-14,...,2.6,15,7,No,Software,Card,2026-02-17,47429.06,170429.06,Adult
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,4.1,34,6,No,Training,Bank Transfer,2024-01-14,52556.00,165556.00,Adult
26,EMP-0027,Imran Hossain,Male,43.0,Sales,Account Manager,Barisal,South,Bangladesh,2022-04-23,...,3.0,7,11,No,Hardware,Card,2026-05-19,52942.47,163442.47,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,EMP-0009,Mehjabin Akter,Female,22.0,Data,Business Analyst,Barisal,South,Bangladesh,2025-12-24,...,4.7,35,1,Yes,Support Plan,Cash,2024-07-10,14827.26,NaN,Adult
22,EMP-0023,Sadia Ahmed,Male,29.0,Data,ML Intern,Chittagong,South-East,Bangladesh,2022-04-11,...,2.9,8,7,Yes,Support Plan,Card,2026-08-10,11401.53,NaN,Adult
58,EMP-0059,Sakib Sultana,Female,30.0,HR,HR Executive,Rajshahi,North-West,Bangladesh,2022-01-15,...,3.5,5,5,No,Software,Bank Transfer,2024-07-21,4326.49,NaN,Adult
87,EMP-0088,Fahim Hossain,Male,28.0,Operations,Supply Chain Officer,Rangpur,North,Bangladesh,2022-03-25,...,3.3,2,9,No,Hardware,Cash,2025-06-18,6802.46,NaN,Adult
111,EMP-0112,Tanjila Ahmed,Male,25.0,Data,Business Analyst,Rangpur,North,Bangladesh,2021-02-05,...,4.5,32,4,No,Training,Mobile Banking,2024-06-17,17408.30,NaN,Adult

In [33]:
df[df["Age"] > 30]  # Filter the DataFrame to show only rows where the 'Age' column is greater than 30

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
5,EMP-0006,Tanjila Khan,Female,37.0,HR,HR Manager,Rajshahi,North-West,Bangladesh,2024-03-02,...,4.8,19,3,Yes,Hardware,Cash,2024-06-24,2052.75,125052.75,Adult
9,EMP-0010,Hasan Islam,Male,36.0,Support,Support Engineer,Rangpur,North,Bangladesh,2017-08-29,...,4.9,34,0,No,Software,Cash,2026-03-02,15979.25,103979.25,Adult
12,EMP-0013,Imran Begum,Female,43.0,Operations,Operations Executive,NaN,NaN,Bangladesh,2022-09-02,...,3.6,27,8,Yes,Software,Cash,2024-11-01,13601.63,81601.63,Adult
13,EMP-0014,Mahin Akter,Male,39.0,Finance,Finance Analyst,Sylhet,North-East,Bangladesh,2017-06-21,...,2.9,11,6,Yes,Hardware,Bank Transfer,2026-04-23,15865.57,101365.57,Adult
14,EMP-0015,Hasan Khan,Female,43.0,HR,Recruiter,Dhaka,Central,Bangladesh,2022-04-12,...,3.2,32,6,No,Software,Cash,2025-06-18,14190.54,72190.54,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,EMP-0119,Mehjabin Miah,Male,34.0,HR,HR Manager,Barisal,South,Bangladesh,2025-08-22,...,4.3,22,6,Yes,Consulting,Bank Transfer,2024-12-22,1673.70,99673.70,Adult
119,EMP-0120,Tanjila Chowdhury,Male,38.0,Sales,Sales Executive,Comilla,East,Bangladesh,2018-02-22,...,2.7,4,3,No,Hardware,Cash,2025-11-10,59655.89,105155.89,Adult
121,EMP-0122,Nusrat Chowdhury,Female,34.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2024-01-28,...,3.3,14,0,No,Software,Mobile Banking,2026-06-19,1913.03,32413.03,Adult
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48,Adult
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,4.4,30,10,No,Training,Cash,2024-07-09,10187.52,90687.52,Adult

In [34]:
df[df["Sales_BDT"] > 100000]  # Filter the DataFrame to show only rows where the 'Sales_BDT' column is greater than 100,000

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
0,EMP-0001,Sakib Akter,Male,28.0,Sales,Sales Executive,Chittagong,South-East,Bangladesh,2024-08-03,...,4.1,34,6,No,Training,Bank Transfer,2024-01-14,52556.00,165556.00,Adult
1,EMP-0002,Farhan Chowdhury,Male,29.0,Finance,Accountant,Barisal,South,Bangladesh,2018-02-23,...,3.2,23,9,No,Software,Cash,2025-04-11,10129.98,98129.98,Adult
3,EMP-0004,Sadia Chowdhury,Male,23.0,Sales,Sales Lead,Barisal,South,Bangladesh,2019-05-21,...,4.7,25,5,No,Hardware,Mobile Banking,2024-07-05,31447.15,136947.15,Adult
4,EMP-0005,Rafi Rahman,Female,NaN,Finance,Payroll Officer,Rangpur,North,Bangladesh,2023-09-09,...,3.2,21,1,No,Training,Card,2026-07-18,13778.66,101778.66,Minor
6,EMP-0007,Nayeem Rahman,Female,25.0,Support,Support Lead,Sylhet,North-East,Bangladesh,2019-12-22,...,3.1,4,5,Yes,Support Plan,Card,2025-03-27,8881.74,131881.74,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,EMP-0120,Tanjila Chowdhury,Male,38.0,Sales,Sales Executive,Comilla,East,Bangladesh,2018-02-22,...,2.7,4,3,No,Hardware,Cash,2025-11-10,59655.89,105155.89,Adult
122,EMP-0123,Hasan Islam,Female,28.0,Sales,Account Manager,Dhaka,Central,Bangladesh,2025-07-27,...,3.9,12,12,No,Support Plan,Bank Transfer,2024-12-25,41665.75,159665.75,Adult
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28,146057.28,Adult
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48,Adult
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,4.4,30,10,No,Training,Cash,2024-07-09,10187.52,90687.52,Adult

In [35]:
df.isnull()  # Check for missing values in the DataFrame

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
124,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
125,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
126,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [36]:
df.isnull().sum()  # Count the number of missing values in each column of the DataFrame

Employee_ID               0
Name                      0
Gender                    0
Age                       5
Department                0
Job_Title                 0
City                      3
Region                    3
Country                   0
Join_Date                 0
Last_Promotion_Date      29
Salary_BDT                5
Bonus_Percent             0
Performance_Score         0
Experience_Years          0
Training_Hours            0
Projects_Completed        0
Remote_Work               0
Employment_Status         0
Education_Level           0
Email                     2
Phone                     0
Manager_ID                8
Sales_BDT                 0
Customer_Rating           0
Overtime_Hours            0
Sick_Days                 0
Has_Missing_Documents     0
Product_Category          0
Payment_Method            0
Order_Date                0
Bonus                     0
Total_Salary              5
Status                    0
dtype: int64

In [38]:
df.dropna(inplace=True)  # Drop rows with missing values from the DataFrame

df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
9,EMP-0010,Hasan Islam,Male,36.0,Support,Support Engineer,Rangpur,North,Bangladesh,2017-08-29,...,4.9,34,0,No,Software,Cash,2026-03-02,15979.25,103979.25,Adult
10,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90,Adult
11,EMP-0012,Tanjila Miah,Female,23.0,Sales,Sales Lead,Rajshahi,North-West,Bangladesh,2018-06-27,...,2.8,8,4,Yes,Software,Card,2025-07-11,48692.91,86692.91,Adult
13,EMP-0014,Mahin Akter,Male,39.0,Finance,Finance Analyst,Sylhet,North-East,Bangladesh,2017-06-21,...,2.9,11,6,Yes,Hardware,Bank Transfer,2026-04-23,15865.57,101365.57,Adult
14,EMP-0015,Hasan Khan,Female,43.0,HR,Recruiter,Dhaka,Central,Bangladesh,2022-04-12,...,3.2,32,6,No,Software,Cash,2025-06-18,14190.54,72190.54,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28,146057.28,Adult
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48,Adult
125,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90,Adult
126,EMP-0026,Sadia Akter,Male,31.0,Finance,Finance Analyst,Khulna,South-West,Bangladesh,2020-12-24,...,4.4,30,10,No,Training,Cash,2024-07-09,10187.52,90687.52,Adult
127,EMP-0071,Fahim Chowdhury,Female,26.0,Operations,Operations Manager,Barisal,South,Bangladesh,2019-02-17,...,3.0,22,0,Yes,Consulting,Mobile Banking,2026-05-18,4417.35,57417.35,Adult

In [39]:
df.isnull().sum()  # Count the number of missing values in each column of the DataFrame

Employee_ID              0
Name                     0
Gender                   0
Age                      0
Department               0
Job_Title                0
City                     0
Region                   0
Country                  0
Join_Date                0
Last_Promotion_Date      0
Salary_BDT               0
Bonus_Percent            0
Performance_Score        0
Experience_Years         0
Training_Hours           0
Projects_Completed       0
Remote_Work              0
Employment_Status        0
Education_Level          0
Email                    0
Phone                    0
Manager_ID               0
Sales_BDT                0
Customer_Rating          0
Overtime_Hours           0
Sick_Days                0
Has_Missing_Documents    0
Product_Category         0
Payment_Method           0
Order_Date               0
Bonus                    0
Total_Salary             0
Status                   0
dtype: int64

In [40]:
df.duplicated()  # Check for duplicate rows in the DataFrame

9      False
10     False
11     False
13     False
14     False
       ...
123    False
124    False
125     True
126     True
127     True
Length: 87, dtype: bool

In [41]:
df.drop_duplicates(inplace=True)  # Drop duplicate rows from the DataFrame
df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
9,EMP-0010,Hasan Islam,Male,36.0,Support,Support Engineer,Rangpur,North,Bangladesh,2017-08-29,...,4.9,34,0,No,Software,Cash,2026-03-02,15979.25,103979.25,Adult
10,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90,Adult
11,EMP-0012,Tanjila Miah,Female,23.0,Sales,Sales Lead,Rajshahi,North-West,Bangladesh,2018-06-27,...,2.8,8,4,Yes,Software,Card,2025-07-11,48692.91,86692.91,Adult
13,EMP-0014,Mahin Akter,Male,39.0,Finance,Finance Analyst,Sylhet,North-East,Bangladesh,2017-06-21,...,2.9,11,6,Yes,Hardware,Bank Transfer,2026-04-23,15865.57,101365.57,Adult
14,EMP-0015,Hasan Khan,Female,43.0,HR,Recruiter,Dhaka,Central,Bangladesh,2022-04-12,...,3.2,32,6,No,Software,Cash,2025-06-18,14190.54,72190.54,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,EMP-0117,Tanjila Chowdhury,Female,28.0,Operations,Operations Manager,Dhaka,Central,Bangladesh,2020-10-04,...,3.2,2,3,No,Consulting,Mobile Banking,2024-06-22,13058.85,146058.85,Adult
117,EMP-0118,Tasnim Rahman,Female,41.0,Data,Data Analyst,Dhaka,Central,Bangladesh,2021-11-17,...,4.9,8,12,Yes,Hardware,Cash,2024-12-02,1370.46,49370.46,Adult
119,EMP-0120,Tanjila Chowdhury,Male,38.0,Sales,Sales Executive,Comilla,East,Bangladesh,2018-02-22,...,2.7,4,3,No,Hardware,Cash,2025-11-10,59655.89,105155.89,Adult
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28,146057.28,Adult
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48,Adult

In [42]:
df.drop_duplicates(subset=["Email"], inplace=True)
df

,Employee_ID,Name,Gender,Age,Department,Job_Title,City,Region,Country,Join_Date,...,Customer_Rating,Overtime_Hours,Sick_Days,Has_Missing_Documents,Product_Category,Payment_Method,Order_Date,Bonus,Total_Salary,Status
9,EMP-0010,Hasan Islam,Male,36.0,Support,Support Engineer,Rangpur,North,Bangladesh,2017-08-29,...,4.9,34,0,No,Software,Cash,2026-03-02,15979.25,103979.25,Adult
10,EMP-0011,Sumaiya Rahman,Female,23.0,HR,HR Manager,Khulna,South-West,Bangladesh,2021-07-12,...,3.2,8,10,No,Training,Bank Transfer,2024-05-28,4379.90,122379.90,Adult
11,EMP-0012,Tanjila Miah,Female,23.0,Sales,Sales Lead,Rajshahi,North-West,Bangladesh,2018-06-27,...,2.8,8,4,Yes,Software,Card,2025-07-11,48692.91,86692.91,Adult
13,EMP-0014,Mahin Akter,Male,39.0,Finance,Finance Analyst,Sylhet,North-East,Bangladesh,2017-06-21,...,2.9,11,6,Yes,Hardware,Bank Transfer,2026-04-23,15865.57,101365.57,Adult
14,EMP-0015,Hasan Khan,Female,43.0,HR,Recruiter,Dhaka,Central,Bangladesh,2022-04-12,...,3.2,32,6,No,Software,Cash,2025-06-18,14190.54,72190.54,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,EMP-0117,Tanjila Chowdhury,Female,28.0,Operations,Operations Manager,Dhaka,Central,Bangladesh,2020-10-04,...,3.2,2,3,No,Consulting,Mobile Banking,2024-06-22,13058.85,146058.85,Adult
117,EMP-0118,Tasnim Rahman,Female,41.0,Data,Data Analyst,Dhaka,Central,Bangladesh,2021-11-17,...,4.9,8,12,Yes,Hardware,Cash,2024-12-02,1370.46,49370.46,Adult
119,EMP-0120,Tanjila Chowdhury,Male,38.0,Sales,Sales Executive,Comilla,East,Bangladesh,2018-02-22,...,2.7,4,3,No,Hardware,Cash,2025-11-10,59655.89,105155.89,Adult
123,EMP-0124,Nayeem Akter,Female,22.0,Sales,Sales Lead,Khulna,South-West,Bangladesh,2017-03-23,...,4.3,9,12,Yes,Support Plan,Bank Transfer,2024-05-28,43057.28,146057.28,Adult
124,EMP-0125,Rakib Chowdhury,Female,31.0,Marketing,Content Marketer,Sylhet,North-East,Bangladesh,2018-10-08,...,3.3,18,2,No,Software,Mobile Banking,2024-03-07,27773.48,123273.48,Adult